version: '3.8'
services:
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - merntalk

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb://mongo:27017/dbCinema"
    depends_on:
      - mongo
    networks:
      - merntalk
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - merntalk
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data:

networks:
  merntalk:
  driver: